version: "3.7"

services:
  php:
    container_name: simple_php
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./src:/src
    restart: unless-stopped

  nginx:
    container_name: simple_nginx
    image: nginx:1.17-alpine
    ports:
      - "80:80"
    #  - "443:443"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
      - ./log/nginx:/var/log/nginx/
      - ./src:/src
    depends_on:
      - php
